export const ORDER_CREATE_REQUEST = 'ORDER_CREATE_REQUEST'
export const ORDER_CREATE_SUCCESS = 'ORDER_CREATE_SUCCESS'
export const ORDER_CREATE_FAIL = 'ORDER_CREATE_FAIL'

export const ORDER_DETAILS_REQUEST = 'ORDER_DETAILS_REQUEST'
export const ORDER_DETAILS_SUCCESS = 'ORDER_DETAILS__SUCCESS'
export const ORDER_DETAILS_FAIL = 'ORDER_DETAILS_FAIL'

export const ORDER_PAYMENT_REQUEST = 'ORDER_PAYMENT_REQUEST'
export const ORDER_PAYMENT_SUCCESS = 'ORDER_PAYMENT__SUCCESS'
export const ORDER_PAYMENT_FAIL = 'ORDER_PAYMENT_FAIL'
export const ORDER_PAYMENT_RESET = 'ORDER_PAYMENT_RESET'

export const ORDER_ALL_ORDERS_REQUEST = 'ORDER_ALL_ORDERS_REQUEST'
export const ORDER_ALL_ORDERS_SUCCESS = 'ORDER_ALL_ORDERS__SUCCESS'
export const ORDER_ALL_ORDERS_FAIL = 'ORDER_ALL_ORDERS_FAIL'

export const ORDER_VIEW_REQUEST = 'ORDER_VIEW_REQUEST'
export const ORDER_VIEW_SUCCESS = 'ORDER_VIEW_SUCCESS'
export const ORDER_VIEW_FAIL = 'ORDER_VIEW_FAIL'

export const ORDER_DELIVER_REQUEST = 'ORDER_DELIVER_REQUEST'
export const ORDER_DELIVER_SUCCESS = 'ORDER_DELIVER_SUCCESS'
export const ORDER_DELIVER_FAIL = 'ORDER_DELIVER_FAIL'
export const ORDER_DELIVER_RESET = 'ORDER_DELIVER_RESET'